drop table PESSOA_TELEFONE;
drop table PESSOA;
drop table ENDERECO;
drop table TELEfone;
drop table TELEFONE_TIPO;

CREATE TABLE ENDERECO (
	ID INTEGER IDENTITY(1,1) NOT NULL PRIMARY KEY,
	LOGRADOURO VARCHAR(256) NOT NULL,
	NUMERO INTEGER NOT NULL,
	CEP INTEGER NOT NULL,
	BAIRRO VARCHAR(50) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO VARCHAR(20) NOT NULL
)

CREATE TABLE TELEFONE_TIPO (
	ID INTEGER IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TIPO VARCHAR(10) NOT NULL
)

CREATE TABLE TELEFONE (
	ID INTEGER IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NUMERO INTEGER NOT NULL,
	DDD INTEGER NOT NULL,
	TIPO INTEGER NOT NULL FOREIGN KEY REFERENCES TELEFONE_TIPO(ID)
)

CREATE TABLE PESSOA (
	ID INTEGER IDENTITY(1,1) NOT NULL PRIMARY KEY,
	NOME VARCHAR(256) NOT NULL,
	CPF BIGINT NOT NULL,
	ENDERECO INTEGER NOT NULL FOREIGN KEY REFERENCES ENDERECO(ID)
)

CREATE TABLE PESSOA_TELEFONE (
	ID_PESSOA INTEGER IDENTITY(1,1) NOT NULL,
	ID_TELEFONE INTEGER NOT NULL,
	CONSTRAINT PESSOA_TELEFONE_PK PRIMARY KEY (ID_PESSOA,ID_TELEFONE) ,
	CONSTRAINT PESSOA_TELEFONE_FK01 FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA (ID),
	CONSTRAINT PESSOA_TELEFONE_FK02 FOREIGN KEY (ID_TELEFONE) REFERENCES TELEFONE (ID)
)

INSERT INTO TELEFONE_TIPO (TIPO) VALUES ('Celular');
INSERT INTO TELEFONE_TIPO (TIPO) VALUES ('Fixo');
INSERT INTO TELEFONE_TIPO (TIPO) VALUES ('Trabalho');
INSERT INTO TELEFONE_TIPO (TIPO) VALUES ('Familiar');

INSERT INTO TELEFONE (NUMERO, DDD, TIPO) VALUES (991679999, 19, 1);
INSERT INTO TELEFONE (NUMERO, DDD, TIPO) VALUES (32560978, 19, 2);

INSERT INTO ENDERECO (LOGRADOURO, NUMERO, CEP, BAIRRO, CIDADE, ESTADO)
VALUES ('Rua Girassol', 400, 13087420, 'Chácara Primavera', 'Campinas', 'SP')
INSERT INTO ENDERECO (LOGRADOURO, NUMERO, CEP, BAIRRO, CIDADE, ESTADO)
VALUES ('Rua das Hortências', 300, 13087420, 'Chácara Primavera', 'Campinas', 'SP')

INSERT INTO PESSOA( CPF, ENDERECO, NOME) VALUES(21521795878,1,'Teste');


SELECT * FROM PESSOA_TELEFONE;
SELECT * FROM PESSOA;
SELECT * FROM ENDERECO;
SELECT * FROM TELEfone;
SELECT * FROM TELEFONE_TIPO;